config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "schools#index"
  resources :schools do
    resources :reviews, only: [ :new, :create ]
    resources :destinations
    resources :scholarships, only: [ :new, :create, :edit, :show, :update ]
  end
  resources :reviews, only: [ :destroy ]
  resources :scholarships, only: [ :index, :destroy ]
  resources :articles
end

app/models/scholarship.rb
class Scholarship < ApplicationRecord
  belongs_to :school

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  def index
    @scholarships = Scholarship.all

    if params[:query].present?
      @scholarships = @scholarships.where('title || description ILIKE ?', "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'scholarships/list', locals: { scholarships: @scholarships }, formats: [:html] }
    end
  end

  def create
    @scholarship = Scholarship.new(scholarship_params)
    # we need `school_id` to associate scholarship with corresponding school
    @school = School.find(params[:school_id])
    @scholarship.school = @school
    if @scholarship.save
      redirect_to school_path(@school)
    else
      render :new
    end
  end

  def new
    @school = School.find(params[:school_id])
    @scholarship = Scholarship.new
  end

  private

  def scholarship_params
    params.require(:scholarship).permit(:title, :description)
  end
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_list.html.erb
<ul data-search-scholarships-target="list">
  <% @scholarships.sort { |a, b| a.school.name <=> b.school.name }.each do |scholarship| %>
  <li class="scholarship-item">
    <div class="scholarship-item-left">
        <div class="logo-wrapper">
          <%= cl_image_tag scholarship.school.logo.key, height: 400, width: 400, crop: :fill if scholarship.school.logo.attached? == true  %>
      </div>
    </div>
    <div class="scholarship-item-right">
      <p><small><%= scholarship.school.name %></small></p>
      <h2><%= scholarship.title %></h2>
      <p class="scholarship-item-description"><%= scholarship.description.truncate(250) %></p>
    </div>

  </li>
  <% end %>
</ul>

app/views/scholarships/index.html.erb
<div id="scholarships-index-page">
  <h1>Scholarships</h1>
  <div data-controller="search-scholarships" class="scholarships-list col-12">
    <%= form_with url: scholarships_path, method: :get, html: { class:
      'mb-4', data: { search_scholarships_target: 'form' } } do |f| %>
      <%= f.text_field :query,
                      class: "form-control",
                      placeholder: 'Search by scholarship type...',
                      value: params[:query],
                      data: {
                        search_scholarships_target: 'input',
                        action: 'keyup->search-scholarships#update'
                      } %>
      <% end %>
    <div>
      <%= render 'scholarships/list' %>
    </div>
  </div>
</div>

app/views/scholarships/new.html.erb
<%= simple_form_for [ @school, @scholarship ] do |f| %>
  <%= f.input :title %>
  <%= f.text_field :description %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>