config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "schools#index"
  resources :schools do
    resources :reviews, only: [ :new, :create ]
    resources :destinations
    resources :scholarships, only: [ :new, :create, :edit, :show, :update ]
  end
  resources :reviews, only: [ :destroy ]
  resources :scholarships, only: [ :index, :destroy ]
  resources :articles
end

app/models/school.rb
class School < ApplicationRecord
  has_many :destinations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :scholarships, dependent: :destroy
  has_one_attached :thumbnail
  has_one_attached :logo
  has_one_attached :cover
  has_many_attached :photos, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_school_type,
    against: [ :name, :school_type ],
    using: {
      tsearch: { prefix: true }
  }
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all

    if params[:query].present?
      @schools = @schools.where('name ILIKE ?', "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'schools/list', locals: { schools: @schools }, formats: [:html] }
    end

    @markers = @schools.geocoded.map do |school|
      {
        lat: school.latitude,
        lng: school.longitude
        # info_window: render_to_string(partial: 'schools/info_window', locals: { school: school })
      }
    end

    if params[:query].present?
    sql_query = "name ILIKE :query OR school_type ILIKE :query"
      @schools = School.where(sql_query, query: "%#{params[:query]}%")
    else
      @schools = School.all
    end
  end

  def show
    @school = School.find(params[:id])
    @review = Review.new
  end

  def create
    @school = School.new(school_params)
    @school.save
    redirect_to school_path(@school)
  end

  def new
    @school = School.new
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    @school.update(school_params)
    redirect_to school_path(@school)
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to schools_path
  end

  private

  def school_params
    params.require(:school).permit(:name, :school_type, :address, :summary, :founded_at, :price, :number_of_pupils, :grade_5_or_above, :aab_or_above, :thumbnail, :logo, :cover)
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_info_window.html.erb
<div>
  <h2><%= school.name %></h2>
  <p><%= school.address %></p>
</div>

app/views/schools/_list.html.erb
<ul data-search-schools-target="list">
  <% @schools.sort { |a, b| a.name <=> b.name }.each do |school| %>
  <li>
    <div class="image-wrapper">
      <%= cl_image_tag school.thumbnail.key, height: 350, width: 450, crop: :fill if school.thumbnail.attached? == true %>
    </div>
    <div class="school-details">
    <p>
      <small><%= school.school_type %></small>
    </p>
    <h2>
      <%= link_to school.name, school_path(school) %>
    </h2>
    <p>
      <small>Founded in <%= school.founded_at %> · <%= school.number_of_pupils %> pupils · £<%= school.price %>/term </small>
    </p>
    <p>
      Achieved Grade 5 or above: <%= school.grade_5_or_above %>%
    </p>
    <p>
      Achieved AAB or above: <%= school.aab_or_above %>%
    </p>
    </div>
  </li>
  <% end %>
</ul>

app/views/schools/_review.html.erb
<p id="review-<%= review.id %>"><%= review.content %> · <%= "#{review.rating}⭐️" %></p>

app/views/schools/edit.html.erb
<%= simple_form_for(@school) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :school_type %>
  <%= f.text_field :school_type %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :summary %>
  <%= f.text_field :summary %>
  <%= f.label :founded_at %>
  <%= f.number_field :founded_at %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.label :grade_5_or_above %>
  <%= f.number_field :grade_5_or_above %>
  <%= f.label :aab_or_above %>
  <%= f.number_field :aab_or_above %>
  <%= f.input :thumbnail, as: :file %>
  <%= f.input :logo, as: :file %>
  <%= f.input :cover, as: :file %>
  <%= f.submit %>
<% end %>

app/views/schools/index.html.erb
<div class="schools-page">
  <div class="schools">
    <h1>Schools in the UK</h1>
    <div data-controller="search-schools">
      <%= form_with url: schools_path, method: :get, html: { class:
        '', data: { search_schools_target: 'form' } } do |f| %>
        <%= f.text_field :query,
                        class: "form-control search-bar",
                        placeholder: 'Type a school title',
                        value: params[:query],
                        data: {
                          search_schools_target: 'input',
                          action: 'keyup->search-schools#update'
                        } %>
      <% end %>
      <%= render 'schools/list' %>
    </div>
  </div>
  <div class="map-section">
    <div
      id="map"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="pk.eyJ1IjoibmljazIzNDIzNDIiLCJhIjoiY2tzMGYybTN1MWpvejJ1cHNrczV4YmFiNyJ9.YOnTvBEhpVi6_j0XJHu3Sw">
    </div>
  </div>
</div>

app/views/schools/new.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <%= simple_form_for(@school) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :school_type %>
      <%= f.text_field :school_type %>
      <%= f.label :address %>
      <%= f.text_field :address %>
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      <%= f.label :founded_at %>
      <%= f.number_field :founded_at %>
      <%= f.label :price %>
      <%= f.number_field :price %>
      <%= f.label :grade_5_or_above %>
      <%= f.number_field :grade_5_or_above %>
      <%= f.label :aab_or_above %>
      <%= f.number_field :aab_or_above %>
      <%= f.input :thumbnail, as: :file %>
      <%= f.input :logo, as: :file %>
      <%= f.input :cover, as: :file %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/schools/show.html.erb
<div class="school-show-page">
  <div class="cover-section">
    <div class="cover-image" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.3)), url('<%= cl_image_path @school.cover.key, height: 400, width: 2240, crop: :fill if @school.cover.attached? == true   %>')">
    </div>
    <div class="cover-section-details">
      <div class="logo-image">
        <%= cl_image_tag @school.logo.key, height: 400, width: 400, crop: :fill if @school.logo.attached? == true  %>
      </div>
      <h1>
        <span>
          <%= @school.school_type %>
        </span><br />
        <%= @school.name %>
      </h1>
    </div>
  </div>

<div class="row">
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <div class="col-8">
    <p>
      <big>Overview</big>
    </p>
    <p>
      Founded in <%= @school.founded_at %> · <%= @school.number_of_pupils %> pupils · £<%= @school.price %>/term
    </p>
    <p>
      Achieved Grade 5 or above: <%= @school.grade_5_or_above %>%
    </p>
    <p>
      Achieved AAB or above: <%= @school.aab_or_above %>%
    </p>
    <p>
      <%= @school.address %>
    </p>
    <p>
      <%= @school.summary %>
    </p>
  </div>
  <div class="school-thumbnail col-4">
    <%= cl_image_tag @school.thumbnail.key, height: 600, width: 800, crop: :fill if @school.thumbnail.attached? == true %>
  </div>
</div>
<%
=begin %>
<ul class="list-group">
  <% @school.destinations.each do |destination| %>
    <li class="list-group-item"><%= destination.university %>: <%= destination.number_of_students %></li>
  <% end %>
</ul>
<ul class="list-group">
  <% @school.scholarships.each do |scholarship| %>
    <li class="list-group-item">
      <%= scholarship.title %>
      <%= scholarship.description %>
      <%= link_to "Remove",
            scholarship_path(scholarship),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>
<%
=end %>
<div>
  <p>
    <big><%= @school.name %> Reviews</big>
  </p>
  <div data-controller="insert-in-list" data-insert-in-list-position-value="beforeend">
    <div id="reviews" data-insert-in-list-target="items">
      <% if @school.reviews.blank? %>
        Be the first to leave a review for <%= @school.name %>
      <% else %>
        <% @school.reviews.each do |review| %>
          <%= render 'review', review: review %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<p>
  <big>Went to <%= @school.name %>? Share Your Experiences</big> (<%= pluralize @school.reviews.size, "review" %>)
</p>
<div class="review-section">
  <div class="review-logo-image">
    <%= cl_image_tag @school.logo.key, height: 400, width: 400, crop: :fill if @school.logo.attached? == true  %>
  </div>
  <div>
    <h4>
      <%= @school.name %>
    </h4>
  </div>
</div>
<%= render 'reviews/form', school: @school, review: @review %>
  <div
      id="map"
      style="width: 100%; height: 480px;"
      data-markers='[{"lat":<%= @school.latitude %>, "lng":<%= @school.longitude %>}]'
      data-mapbox-api-key="pk.eyJ1IjoibmljazIzNDIzNDIiLCJhIjoiY2tzMGYybTN1MWpvejJ1cHNrczV4YmFiNyJ9.YOnTvBEhpVi6_j0XJHu3Sw">
  </div>
  <p>
    <big><%= @school.address %></big>
  </p>
  <div>
    <%= link_to 'Edit', edit_school_path(@school) %> |
    <%= link_to 'Back', schools_path %> |
    <%= link_to "Delete #{@school.name}",
              school_path(@school),
              method: :delete,
              data: { confirm: "Are you sure?" } %> |
    <%= link_to 'Add a destination', new_school_destination_path(@school) %> |
    <%= link_to 'Add a scholarship', new_school_scholarship_path(@school) %>
  </div>
</div>